
package org.soap.cli;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PessoaServiceImplService", targetNamespace = "http://soap.com/", wsdlLocation = "http://localhost:8888/ws/pessoa?wsdl")
public class PessoaServiceImplService
    extends Service
{

    private final static URL PESSOASERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.soap.cli.PessoaServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.soap.cli.PessoaServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8888/ws/pessoa?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8888/ws/pessoa?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PESSOASERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public PessoaServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PessoaServiceImplService() {
        super(PESSOASERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://soap.com/", "PessoaServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns PessoaService
     */
    @WebEndpoint(name = "PessoaServiceImplPort")
    public PessoaService getPessoaServiceImplPort() {
        return super.getPort(new QName("http://soap.com/", "PessoaServiceImplPort"), PessoaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PessoaService
     */
    @WebEndpoint(name = "PessoaServiceImplPort")
    public PessoaService getPessoaServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.com/", "PessoaServiceImplPort"), PessoaService.class, features);
    }

}
