
package org.soap.cli;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PessoaService", targetNamespace = "http://soap.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PessoaService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean addPessoa(
        @WebParam(name = "arg0", partName = "arg0")
        Pessoa arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean deletePessoa(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @return
     *     returns org.soap.cli.PessoaArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public PessoaArray getAllPessoas();

    /**
     * 
     * @param arg0
     * @return
     *     returns org.soap.cli.Pessoa
     */
    @WebMethod
    @WebResult(partName = "return")
    public Pessoa getPessoa(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

}
